definitions:
  request.Number:
    properties:
      count:
        type: integer
    type: object
  utils.ErrorCode:
    properties:
      code:
        type: integer
      message:
        type: string
      name:
        type: string
      remark:
        type: string
    type: object
info:
  contact: {}
paths:
  /checkout/v1/number:
    get:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorCode'
      summary: Collect backtest order from bot
      tags:
      - Number
    put:
      description: Update count
      parameters:
      - description: Number
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/request.Number'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrorCode'
      summary: Update count
      tags:
      - Number
swagger: "2.0"
